/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZhIndexRouteImport } from './routes/zh/index'
import { Route as ZhServicesRouteImport } from './routes/zh/services'
import { Route as ZhProjectsRouteImport } from './routes/zh/projects'
import { Route as ZhContactRouteImport } from './routes/zh/contact'
import { Route as ZhAboutRouteImport } from './routes/zh/about'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/zh/',
  path: '/zh/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhServicesRoute = ZhServicesRouteImport.update({
  id: '/zh/services',
  path: '/zh/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhProjectsRoute = ZhProjectsRouteImport.update({
  id: '/zh/projects',
  path: '/zh/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhContactRoute = ZhContactRouteImport.update({
  id: '/zh/contact',
  path: '/zh/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhAboutRoute = ZhAboutRouteImport.update({
  id: '/zh/about',
  path: '/zh/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/contact': typeof ZhContactRoute
  '/zh/projects': typeof ZhProjectsRoute
  '/zh/services': typeof ZhServicesRoute
  '/zh/': typeof ZhIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/contact': typeof ZhContactRoute
  '/zh/projects': typeof ZhProjectsRoute
  '/zh/services': typeof ZhServicesRoute
  '/zh': typeof ZhIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/contact': typeof ZhContactRoute
  '/zh/projects': typeof ZhProjectsRoute
  '/zh/services': typeof ZhServicesRoute
  '/zh/': typeof ZhIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/zh/about'
    | '/zh/contact'
    | '/zh/projects'
    | '/zh/services'
    | '/zh/'
    | '/api/public/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/zh/about'
    | '/zh/contact'
    | '/zh/projects'
    | '/zh/services'
    | '/zh'
    | '/api/public/contact'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/zh/about'
    | '/zh/contact'
    | '/zh/projects'
    | '/zh/services'
    | '/zh/'
    | '/api/public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZhAboutRoute: typeof ZhAboutRoute
  ZhContactRoute: typeof ZhContactRoute
  ZhProjectsRoute: typeof ZhProjectsRoute
  ZhServicesRoute: typeof ZhServicesRoute
  ZhIndexRoute: typeof ZhIndexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/': {
      id: '/zh/'
      path: '/zh'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/services': {
      id: '/zh/services'
      path: '/zh/services'
      fullPath: '/zh/services'
      preLoaderRoute: typeof ZhServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/projects': {
      id: '/zh/projects'
      path: '/zh/projects'
      fullPath: '/zh/projects'
      preLoaderRoute: typeof ZhProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/contact': {
      id: '/zh/contact'
      path: '/zh/contact'
      fullPath: '/zh/contact'
      preLoaderRoute: typeof ZhContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/about': {
      id: '/zh/about'
      path: '/zh/about'
      fullPath: '/zh/about'
      preLoaderRoute: typeof ZhAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZhAboutRoute: ZhAboutRoute,
  ZhContactRoute: ZhContactRoute,
  ZhProjectsRoute: ZhProjectsRoute,
  ZhServicesRoute: ZhServicesRoute,
  ZhIndexRoute: ZhIndexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
